"""
Analysis of the simulated benchmark (Section 4.9).

Pre-specified in notes/synth/design.md before any model was trained:
  primary test   MSWEA on the coupled condition: paired AUROC difference
                 full - MSWEA-off over 5 series x 3 seeds (n = 15), two-sided
                 exact Wilcoxon, Holm-corrected over the two MSWEA tests
                 (coupled, independent).
  "MSWEA helps"  Holm p < 0.05, positive mean difference, and a positive
                 seed-averaged difference on at least 4 of the 5 series.
Also reported: the same statistics for Fusionformer vs LSTM, and the
reference detectors from synth_check.py.

Writes notes/synth/all_runs_synth.csv and notes/synth/synth_stats.txt

Author: Nachiket Magadum
MSc AI dissertation, Brunel University London, 2026.
"""
import re
from pathlib import Path

import numpy as np
import pandas as pd

from analyse_final import test, holm, fmt, unit_level, _get

SYN = Path("notes/synth")


def parse():
    rows = []
    for p in sorted(SYN.glob("*.txt")):
        m = re.match(r"^ff_true_(full|no_mswea_pm|no_mswea)_synth_(coupled|independent)_(\d)_seed(\d+)$", p.stem)
        if m:
            v, cond, u, s = m.groups()
        else:
            m = re.match(r"^lstm_baseline_synth_(coupled|independent)_(\d)_seed(\d+)$", p.stem)
            if not m:
                continue
            cond, u, s = m.groups(); v = "lstm"
        t = p.read_text()
        rows.append(dict(variant=v, condition=cond, id=u, seed=int(s),
                         auroc=_get(t, r"Test AUROC:\s*([\d.]+)"),
                         pr_auc=_get(t, r"Test PR-AUC:\s*([\d.]+)"),
                         mae=_get(t, r"Test forecast MAE:\s*([\d.]+)")))
    return pd.DataFrame(rows)


def paired(df, cond, a, b, metric="auroc"):
    A = df[(df.variant == a) & (df.condition == cond)].set_index(["id", "seed"])[metric]
    B = df[(df.variant == b) & (df.condition == cond)].set_index(["id", "seed"])[metric]
    return pd.concat([A, B], axis=1, keys=["a", "b"]).dropna()


def main():
    df = parse()
    df.to_csv(SYN / "all_runs_synth.csv", index=False)
    out = ["SIMULATED BENCHMARK (generated by analyse_synth.py)", "=" * 74,
           df.groupby(["condition", "variant"])[["auroc", "pr_auc", "mae"]].agg(["mean", "std", "count"]).round(4).to_string(), ""]
    res = []
    for cond in ("coupled", "independent"):
        j = paired(df, cond, "full", "no_mswea")
        res.append((f"MSWEA on {cond}", "full", "no_mswea", j, test(j.a - j.b)))
    adj = holm([r[4]["p"] for r in res])
    out.append("MSWEA (primary test = coupled; Holm over the two MSWEA tests)")
    for (name, a, b, j, s), pa in zip(res, adj):
        out.append(fmt(name, a, b, j, s, pa)); out.append(unit_level(j))
        units_pos = int(((j.groupby(level=0).mean().a - j.groupby(level=0).mean().b) > 0).sum())
        verdict = pa < 0.05 and s["mean"] > 0 and units_pos >= 4
        out.append(f"  pre-specified verdict 'MSWEA helps': {verdict}")
    if (df.variant == "no_mswea_pm").any():
        out.append("")
        out.append("PARAMETER-MATCHED CONTROL (added after review, not pre-specified; Holm over these two tests)")
        pm = []
        for cond in ("coupled", "independent"):
            j = paired(df, cond, "full", "no_mswea_pm")
            pm.append((f"MSWEA vs parameter-matched MSWEA-off on {cond}", "full", "no_mswea_pm", j, test(j.a - j.b)))
        for (name, a, b, j, s), pa in zip(pm, holm([r[4]["p"] for r in pm])):
            out.append(fmt(name, a, b, j, s, pa)); out.append(unit_level(j))
    out.append("")
    out.append("FUSIONFORMER vs LSTM (AUROC, and MAE with positive = Fusionformer lower error)")
    for cond in ("coupled", "independent"):
        j = paired(df, cond, "full", "lstm"); out.append(fmt(f"AUROC FF vs LSTM on {cond}", "full", "lstm", j, test(j.a - j.b)))
        j = paired(df, cond, "lstm", "full", "mae"); out.append(fmt(f"MAE LSTM vs FF on {cond}", "lstm", "full", j, test(j.a - j.b)))
    ref = SYN / "reference_detectors.csv"
    if ref.exists():
        r = pd.read_csv(ref)
        out += ["", "REFERENCE DETECTORS (mean over the 5 series)",
                r.groupby("condition").mean(numeric_only=True).round(4).to_string()]
    text = "\n".join(out)
    (SYN / "synth_stats.txt").write_text(text + "\n")
    print(text)


if __name__ == "__main__":
    main()
